### ISSUE TITLE
Auto reload does not work with template

### ISSUE THREAD

**Issue by arduino-man** [neutralinojs/neutralinojs-zero#1]
Hi, I am new to Neutralinojs and like it so far.

I've found that auto code reloading works when I use `neu create myapp` but does not work when I use `npx @neutralinojs/neu create simplegame2 --template neutralinojs/neutralinojs-zero`

Not sure if I am missing some setting somewhere.

Thanks

**Comment by Soupertonic** [comment]
I know this reply is pretty late but I hope this will help somebody that encounters the same issue. I found the solution. I'll take the liberty to just copy paste from the documentation:

> Registers auto-reload event handler if the --neu-dev-auto-reload flag (the neu run command sets this flag) is provided.

That is from the `Neutralino.init()` section. You have to call the init function to enable auto reload. But this won't work if we don't make a few changes to the configuration file.

`neutralino.config.json`
```diff
+ "tokenSecurity": "one-time",
+ "nativeAllowList": [
+   "app.*",
+   "os.*",
+   "debug.log"
+],
```

`index.html`
```diff
  <body>
    It works 🚀
    <script src="neutralino.js"></script>
+   <script>Neutralino.init()</script>
  </body>
```

**Comment by shalithasuranga** [comment]
Closing this issue since it's already answered. Thanks so much for reporting this issue and starting a discussion :tada:
